using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//UNITY MonoBehavior SINIFI,HER BIR UNITY BILESENININ TURETILDIGI TEMEL BIR SINIFTIR.
//BIR BILESEN MonoBehavior SINIFINDAN TURETILMEK ZORUNDADIR.
//PUBLIC(HERKESE ACIK) CLASS(SINIF) FollowPlayerX (KOMUT DOSYAMIZIN ADI) : MonoBehaviour(UNITY SINIFI)
public class FollowPlayerX : MonoBehaviour
{
    //PUBLIC(HERKESE ACIK) GAMEOBJECT((DEGISKENIN TURU)OYUN NESNESI) PLAYER(DEGISKENIMIZIN ADI);
    public GameObject plane;
    //PRIVATE(OZEL) VECTOR3(DEGISKENIN TURU(3 YON)) OFFSET(DEGISKENIMIZIN ADI) = NEW VECTOR3(YENI 3 YON)(30, 0, 10);
    private Vector3 offset = new Vector3(30, 0, 10);

    //VOID(BOSLUK):BURASININ FONKSIYON IFADESI OLDUGUNU SOYLER.
    //VOID LATEUPDATE() FONKSIYONU NEDENIYLE KAMERAMIZDA UCAGIMIZ OLDUGUNDAN COK DAHA DUZGUN VE AKICI HAREKET EDECEK.
    //UNITYDE LATEUPDATE()(GEC GUNCELLEME) FONKSIYONU,HER FRAME"IN SONUNDA CAGRILAN BIR MONOBEHAVIOUR FONKSIYONUDUR.
    //UPDATE() FONKSIYONUNDAN FARKLI OLARAK,LATEUPDATE() FONKSIYONU,TUM DIGER GUNCELLEME ISLEMLERININ TAMAMLANDIGINDAN VE KAMERA VE DIGER NESNELERIN KONUMLARI GUNCELLENDIGINDEN EMIN OLUR.
    //BU NEDENLE,KAMERA HAREKETI VEYA NESNE KONUMLANDIRMASI GIBI ISLEMLERI GERCEKLESTIRMEK ICIN LATEUPDATE() FONKSIYONU KULLANILABILIR.
    //BU,DIGER GUNCELLEME ISLEMLERINDEN SONRA CALISTIGINDAN,NESNELERIN KONUMLARINA UYGUN BIR SEKILDE ISLEM YAPMAYI SAGLAR VE BOYLECE DAHA AKICI BIR OYUN DENEYIMI SUNAR.
    void LateUpdate()
    {
//transform(KAMERANIN TRANSFORMU).POSITION(KAMERANIN KONUMU) (=)ESITLE PLANE((UCAK)OYUN NESNESININ ADI).TRANSFORM(PLANE NESNESININ TRANSFORMU).POSITION(PLANE ADINDAKI NESNENIN KONUMU) + OFFSET(DEGISKENIMIZIN ADI));
        transform.position = plane.transform.position + offset;
    }
}





















